"""add visibility enum

Revision ID: 25ff1950b671
Revises: 6c8152c2c4a6
Create Date: 2026-07-23 21:58:21.907640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ff1950b671'
down_revision: Union[str, Sequence[str], None] = '6c8152c2c4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('echoes', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PUBLIC', 'PRIVATE', name='visibility'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('echoes', 'visibility',
               existing_type=sa.Enum('PUBLIC', 'PRIVATE', name='visibility'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
